server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*



#Customer route
spring.cloud.gateway.routes[0].id=customer
spring.cloud.gateway.routes[0].uri=lb://customer-service
spring.cloud.gateway.routes[0].predicates[0]=path=/api/v1/customers/**

#Account Route

spring.cloud.gateway.routes[1].id=account
spring.cloud.gateway.routes[1].uri=lb://account-service
spring.cloud.gateway.routes[1].predicates[0]=path=/api/v1/accounts/**


#Payment Route

spring.cloud.gateway.routes[2].id=payment
spring.cloud.gateway.routes[2].uri=lb://payment-service
spring.cloud.gateway.routes[2].predicates[0]=path=/api/v1/payments/**

#Settlement Route

spring.cloud.gateway.routes[3].id=settlement
spring.cloud.gateway.routes[3].uri=lb://settlement-service
spring.cloud.gateway.routes[3].predicates[0]=path=/api/v1/settlements/**

#Notification Route

spring.cloud.gateway.routes[4].id=notification
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=path=/api/v1/notifications/**
