server.port=8083

#eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#postgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/finpay_payment
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.ddl-format_sql=true
#jwt.secret=FinPayEnterpriseSecretKey2026SpringBootJWTAuthenticationSecureKey987654321
jwt.secret=${JWT_SECRET}


management.endpoints.web.exposure.include=*
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml